name: CI/CD for Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar o Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Validar o arquivo docker-compose.yml
      - name: Validate docker-compose.yml
        run: docker-compose config

      # Buildar os serviços definidos no docker-compose.yml
      - name: Build Docker Compose services
        run: docker-compose build

      # Testar o serviço "test" definido no docker-compose.yml
      - name: Run tests
        run: docker-compose run --rm test
