name: CI/CD for Docker Compose

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Buildar os serviços definidos no docker-compose.yml
      - name: Build Docker Compose services
        run: docker-compose build

      # Testar o serviço "test" definido no docker-compose.yml
      - name: Run tests
        run: docker-compose run --rm test