name: Continuos Test

on: push

jobs:
  continuos-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkou@v3
      - name: Using Node.jobs
        uses: actions/setup-node@v2
        with:
          node-veersion: 20.x
      - name: run Test
        run: |
          npm install
          npm test